[{
        url: 'https://api.github.com/repos/githubuserdemo/pullrequestupdatertest/pulls/3',
        id: 1142746674,
        node_id: 'PR_kwDOIijwDM5EHO4y',
        html_url: 'https://github.com/githubuserdemo/pullrequestupdatertest/pull/3',
        diff_url: 'https://github.com/githubuserdemo/pullrequestupdatertest/pull/3.diff',
        patch_url: 'https://github.com/githubuserdemo/pullrequestupdatertest/pull/3.patch',
        issue_url: 'https://api.github.com/repos/githubuserdemo/pullrequestupdatertest/issues/3',
        number: 3,
        state: 'open',
        locked: false,
        title: 'Update README.md',
        user: {
            login: 'wechuli',
            id: 15605874,
            node_id: 'MDQ6VXNlcjE1NjA1ODc0',
            avatar_url: 'https://avatars.githubusercontent.com/u/15605874?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/wechuli',
            html_url: 'https://github.com/wechuli',
            followers_url: 'https://api.github.com/users/wechuli/followers',
            following_url: 'https://api.github.com/users/wechuli/following{/other_user}',
            gists_url: 'https://api.github.com/users/wechuli/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/wechuli/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/wechuli/subscriptions',
            organizations_url: 'https://api.github.com/users/wechuli/orgs',
            repos_url: 'https://api.github.com/users/wechuli/repos',
            events_url: 'https://api.github.com/users/wechuli/events{/privacy}',
            received_events_url: 'https://api.github.com/users/wechuli/received_events',
            type: 'User',
            site_admin: true
        },
        body: 'sasa',
        created_at: '2022-12-02T05:00:44Z',
        updated_at: '2022-12-02T05:00:44Z',
        closed_at: null,
        merged_at: null,
        merge_commit_sha: 'e5ec4753d7ab13db79c1960c1c5a0935df354bf5',
        assignee: null,
        assignees: [],
        requested_reviewers: [],
        requested_teams: [],
        labels: [],
        milestone: null,
        draft: false,
        commits_url: 'https://api.github.com/repos/githubuserdemo/pullrequestupdatertest/pulls/3/commits',
        review_comments_url: 'https://api.github.com/repos/githubuserdemo/pullrequestupdatertest/pulls/3/comments',
        review_comment_url: 'https://api.github.com/repos/githubuserdemo/pullrequestupdatertest/pulls/comments{/number}',
        comments_url: 'https://api.github.com/repos/githubuserdemo/pullrequestupdatertest/issues/3/comments',
        statuses_url: 'https://api.github.com/repos/githubuserdemo/pullrequestupdatertest/statuses/cbf57de0bdfc5ff79424acffbe3534c57a8c74a2',
        head: {
            label: 'githubuserdemo:toclose',
            ref: 'toclose',
            sha: 'cbf57de0bdfc5ff79424acffbe3534c57a8c74a2',
            user: [Object],
            repo: [Object]
        },
        base: {
            label: 'githubuserdemo:main',
            ref: 'main',
            sha: '7128170a8f00c304a4b67215083f1b316a358be4',
            user: [Object],
            repo: [Object]
        },
        _links: {
            self: [Object],
            html: [Object],
            issue: [Object],
            comments: [Object],
            review_comments: [Object],
            review_comment: [Object],
            commits: [Object],
            statuses: [Object]
        },
        author_association: 'CONTRIBUTOR',
        auto_merge: null,
        active_lock_reason: null
    },
    {
        url: 'https://api.github.com/repos/githubuserdemo/pullrequestupdatertest/pulls/1',
        id: 1142265138,
        node_id: 'PR_kwDOIijwDM5EFZUy',
        html_url: 'https://github.com/githubuserdemo/pullrequestupdatertest/pull/1',
        diff_url: 'https://github.com/githubuserdemo/pullrequestupdatertest/pull/1.diff',
        patch_url: 'https://github.com/githubuserdemo/pullrequestupdatertest/pull/1.patch',
        issue_url: 'https://api.github.com/repos/githubuserdemo/pullrequestupdatertest/issues/1',
        number: 1,
        state: 'open',
        locked: false,
        title: 'Update README.md',
        user: {
            login: 'wechuli',
            id: 15605874,
            node_id: 'MDQ6VXNlcjE1NjA1ODc0',
            avatar_url: 'https://avatars.githubusercontent.com/u/15605874?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/wechuli',
            html_url: 'https://github.com/wechuli',
            followers_url: 'https://api.github.com/users/wechuli/followers',
            following_url: 'https://api.github.com/users/wechuli/following{/other_user}',
            gists_url: 'https://api.github.com/users/wechuli/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/wechuli/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/wechuli/subscriptions',
            organizations_url: 'https://api.github.com/users/wechuli/orgs',
            repos_url: 'https://api.github.com/users/wechuli/repos',
            events_url: 'https://api.github.com/users/wechuli/events{/privacy}',
            received_events_url: 'https://api.github.com/users/wechuli/received_events',
            type: 'User',
            site_admin: true
        },
        body: 'dsds',
        created_at: '2022-12-01T18:44:02Z',
        updated_at: '2022-12-01T18:44:02Z',
        closed_at: null,
        merged_at: null,
        merge_commit_sha: '6113f9c9e1d31eb3c01da309bb6da3cba6a19ff0',
        assignee: null,
        assignees: [],
        requested_reviewers: [],
        requested_teams: [],
        labels: [],
        milestone: null,
        draft: false,
        commits_url: 'https://api.github.com/repos/githubuserdemo/pullrequestupdatertest/pulls/1/commits',
        review_comments_url: 'https://api.github.com/repos/githubuserdemo/pullrequestupdatertest/pulls/1/comments',
        review_comment_url: 'https://api.github.com/repos/githubuserdemo/pullrequestupdatertest/pulls/comments{/number}',
        comments_url: 'https://api.github.com/repos/githubuserdemo/pullrequestupdatertest/issues/1/comments',
        statuses_url: 'https://api.github.com/repos/githubuserdemo/pullrequestupdatertest/statuses/17a7fd6c2edcd32c146ed40933e4a4b55fd58db6',
        head: {
            label: 'githubuserdemo:dev',
            ref: 'dev',
            sha: '17a7fd6c2edcd32c146ed40933e4a4b55fd58db6',
            user: [Object],
            repo: [Object]
        },
        base: {
            label: 'githubuserdemo:main',
            ref: 'main',
            sha: '7128170a8f00c304a4b67215083f1b316a358be4',
            user: [Object],
            repo: [Object]
        },
        _links: {
            self: [Object],
            html: [Object],
            issue: [Object],
            comments: [Object],
            review_comments: [Object],
            review_comment: [Object],
            commits: [Object],
            statuses: [Object]
        },
        author_association: 'CONTRIBUTOR',
        auto_merge: null,
        active_lock_reason: null
    }
]